version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    build: 
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kuyasawa-hp
    volumes:
      - kuyasawa-hp-data:/var/lib/postgresql/data
volumes:
  kuyasawa-hp-data:
    external: true